### ISSUE TITLE
请问能支持多节点吗？

### ISSUE THREAD

**Issue by 2lifetop** [Har-Kuun/OneClickCDN#1]
一个主控，几个受控端这样子，然后对于多个服务器源站可以进行权重配置就更好了

**Comment by Har-Kuun** [comment]
这个功能需要额外安装Traffic Control主控 [https://traffic-control-cdn.readthedocs.io/en/latest/index.html](https://traffic-control-cdn.readthedocs.io/en/latest/index.html)

**Comment by dmuxue** [comment]
可以汉化和提供删除的选项吗
使用说明做成文本放入脚本选项

**Comment by dmuxue** [comment]
ats是很好的cdn软件

**Comment by m1911** [comment]
@Har-Kuun ats 本身就自带了集群功能吧

**Comment by Har-Kuun** [comment]
> 可以汉化和提供删除的选项吗
> 使用说明做成文本放入脚本选项

已汉化 https://raw.githubusercontent.com/Har-Kuun/OneClickCDN/master/translation/translated_scripts/OneClickCDN_zh-CN.sh

删除网站与卸载的功能也已经实现

**Comment by Har-Kuun** [comment]
> @Har-Kuun ats 本身就自带了集群功能吧

本身不提供集群功能，不过和ATS配套的Traffic Control提供了这个功能。
