### ISSUE TITLE
using latest apache traffic server

### ISSUE THREAD

**Issue by rsidhaarth** [Har-Kuun/OneClickCDN#13]
Hi There,

The script is using the old version of the ATS. Is it possible for you to make the script work with the latest ATS?

Thanks

**Comment by Har-Kuun** [comment]
Yes, you can modify the first few lines of the script to use a different version of the ATS.  The script has been tested for the latest 8.x versions.  It should also work for 9.x version, but might be buggy for 10.x versions.

Thanks for pointing this out.
