### ISSUE TITLE
CentOS 7下安装出现错误

### ISSUE THREAD

**Issue by WangWenBin2017** [Har-Kuun/OneClickCDN#3]
腾讯云国内1h1g的小鸡，拿来试试手，分了2000MB的swap，但是装的时候出现错误：
`----------------------------------------------------------------------
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/trafficserver-8.0.8/src/tscpp/api'
make[2]: Leaving directory '/root/trafficserver-8.0.8/src/tscpp/api'
make[2]: Entering directory '/root/trafficserver-8.0.8/src'
  CXXLD    traffic_top/traffic_top
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
traffic_top/traffic_top-traffic_top.o: In function `std::string::_Rep::_M_dispose(std::allocator<char> const&) [clone .isra.38] [clone .part.39]':
/opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:81: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o: In function `write_data(void*, unsigned long, unsigned long, void*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3322: undefined reference to `response'
traffic_top/traffic_top-traffic_top.o: In function `write_data(void*, unsigned long, unsigned long, void*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.tcc:758: undefined reference to `response'
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.tcc:758: undefined reference to `response'
traffic_top/traffic_top-traffic_top.o: In function `write_data(void*, unsigned long, unsigned long, void*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3322: undefined reference to `response'
traffic_top/traffic_top-traffic_top.o: In function `write_data(void*, unsigned long, unsigned long, void*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.tcc:763: undefined reference to `response'
traffic_top/traffic_top-traffic_top.o:/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3205: more undefined references to `response' follow
traffic_top/traffic_top-traffic_top.o: In function `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:81: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o: In function `std::string::reserve(unsigned long)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:81: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o: In function `std::_Rb_tree<std::string, std::pair<std::string const, LookupItem>, std::_Select1st<std::pair<std::string const, LookupItem> >, std::less<std::string>, std::allocator<std::pair<std::string const, LookupItem> > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, LookupItem> >*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:1870: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o: In function `std::_Rb_tree<std::string, std::pair<std::string const, std::string>, std::_Select1st<std::pair<std::string const, std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, std::string> >*)':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:1870: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o: In function `Stats::~Stats()':
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:1870: undefined reference to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))'
traffic_top/traffic_top-traffic_top.o:/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:1870: more undefined references to `__gthrw___pthread_key_create(unsigned int*, void (*)(void*))' follow
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2016: traffic_top/traffic_top] Error 1
make[2]: Leaving directory '/root/trafficserver-8.0.8/src'
make[1]: *** [Makefile:2656: install-recursive] Error 1
make[1]: Leaving directory '/root/trafficserver-8.0.8/src'
make: *** [Makefile:860: install-recursive] Error 1`

**Comment by Har-Kuun** [comment]
请问是用的官方镜像还是DD的镜像？大概率是缺了什么依赖包……我自己装过轻量云官方镜像，没有出现过这样的问题，如果你有DD的镜像地址，麻烦告知一下哈

**Comment by WangWenBin2017** [comment]
额，官方的镜像，没有DD，那个discuzq的镜像，基于centos7的，明天我试试控制台直接重装centos7吧

**Comment by WangWenBin2017** [comment]
还有我已经把原来的LNMP卸载掉了，不知道是不是和没卸载干净有关系，总之我先试试，可能不是这个脚本的原因，谢谢了

**Comment by Har-Kuun** [comment]
嗯嗯，我估计是discuzq镜像的原因，如果换了镜像还有问题的话再来问我哈
