### ISSUE TITLE
默认添加的cdn站点就是HTTPS

### ISSUE THREAD

**Issue by w796933** [Har-Kuun/OneClickCDN#4]
默认添加的cdn站点就是HTTPS   ， 能不能 有个选择  添加cdn 的站点 普通的http   协议。  或者HTTPS协议。  如果用 HTTPS 协议就留提示是否强制跳转到HTTPS     
现在要用http 协议。      要修改remap.conf   把   HTTPS  改成http

**Comment by Har-Kuun** [comment]
添加站点的时候有询问https还是http的呀

**Comment by w796933** [comment]
我选择http啦，但是还是https啊  你试试

Har-Kuun <notifications@github.com> 于 2020年8月1日周六 上午10:11写道：

**Comment by Har-Kuun** [comment]
看到了，确实是的，现在已修复，感谢~
